services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: game_class
    ports:
      - "8080:8080" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal/${DB_NAME}?${DB_USER}=root&password=${DB_PASS}
      TOKEN_PASS: ${TOKEN_PASS}
      LOGIN_VALIDATE_HOURS: ${LOGIN_VALIDATE_HOURS}
